The following circuit is converter type BUCK-BOOST running in DCM mode.

```{python}
#|echo: false 
#|warning: true
#|error: true
#|output: true
#|include: true
from contextlib import redirect_stdout, redirect_stderr
import io
import warnings
import logging
from lcapy import *

warnings.filterwarnings('ignore')
logging.getLogger('lcapy').setLevel(logging.ERROR)
with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
    converter_P2 = Circuit(r"""
    #create voltage source
        V ._plus  0 {V_g  }; down, size=2
    #create inductor
        L ._1 ._2; down, l= L, size=2, i>^=i(t)
    #create diode
        D ._A ._K; left, l= D, size=2
    #create capacitor
        C ._1 ._2; down, l= C, size=2
    #create resistor
        R ._1 ._2; down, l= R, size=2, v=V
    #create transistor-NMOS
        M ._D ._G ._S nmos; up, l= Q1, size=2
    #create connections:
    # connect voltage source to transistor
        W V._plus M._D; right, size=1
    # connect transistor to inductor
        W M._S L._1; steps=-|, free
    # connect transistor to diode
        W M._S D._K; right, size=0
    # connect diode to capacitor
        W D._A C._1; steps=-|, free
    # connect diode to resistor
        W D._A R._1; steps=--|, free
    # connecting grounds
        #ground inductor
        W 0 L._2; right, size=3
        #ground capacitor
        W L._2 C._2; right, size=2
        #ground resistor
        W C._2 R._2; right
        ; autoground=false, draw_nodes=connections, label_ids=false, label_nodes=alpha, european voltages""")
converter_P2.draw(svg=True)
```

-   All the elements are ideal.
-   All the losses are neglected.
-   The transistor is conduction at time interval $\left[0, D_{1}T_{s}\right]$.
-   DCM mode.

## Question A:

What is the condition for the converter to operate in DCM mode?

::: callout-note
### The work principles of the converter for DCM mode are as follows:

-   The voltages and currents in the system are periodic waves with period $T_{s}$, as result of that:

    -   The average voltage across the inductor in one period is zero.
    -   The average current through the capacitor in one period is zero.

-   The following connections between the temporal waveforms and their average over period for all waves (voltages and currents): $$ \int_{0}^{T_{s}} x\left(\tau \right)d\tau = T_{s} \cdot X = \int_{0}^{T_{s}}X d\tau$$

    in addition to that, for capacitor voltages (assuming small ripple):

    $$
      \begin{gathered}
      \int_{0}^{D_{1}T_{s}} v\left(\tau\right)d\tau \approx D_{1}T_{s} \cdot V \\
      \int_{D_{1}T_{s}}^{\left(D_{1}+D_{2}\right)}v\left(\tau\right)d\tau \approx D_{2}T_{s} \cdot V \\
      \int_{D_{2}T_{s}}^{\left(D_{2}+D_{3}\right)T_{s}} v\left(\tau\right)d\tau \approx D_{3}T_{s} \cdot V
      \end{gathered}
      $$
:::

First, I'll analyze the converter as it was operating in CCM mode, which will results into having equation for the average current through the inductor, $I$, and the equation of the current ripple through the inductor, $\Delta i$, having those two equations will allow me the derive the condition for operation in DCM mode by solving the inequality: $I \lt \Delta I \Longrightarrow\text{DCM mode}$.

### $\underline{\text{phase 1, }0 \lt t \lt D_{1}T_{s}\text{:}}$

The switch is ON, the inductor is connected directly to the voltage source:

$$v_L\left(t\right)=V_g$$

The diode is reverse biased because the voltage source is connected to the cathode while the output voltage, which in buck boost is negative is connected to the diode's anode, therefor, there is no current loop between the capacitor and the voltage source, but also, [there is no current loop between the capacitor and the inductor]{.mark}. however, in CCM, the output voltage across the load resistor is constant (Small-Ripple Voltage approximation), and applying KCL on the output node (negative voltage) result into current loop between the load resistor and the capacitor, with the sign convention where positive capacitor current flows from the output node to ground:

$$
i_{C}\left(t\right)=-\frac{v\left(t\right)}{R}\approx -\frac{V}{R}
$$

### $\underline{\text{phase 2, }D_{1}T_{s} \le t \lt T_{s}\text{:}}$

The switch is OFF, the inductor is now connected to the voltage output (diode voltage drop assumed to be neglect):

$$
v_{L}\left(t\right)=v\left(t\right)\approx V
$$

because current must be continues, the current which flowed through the inductor, $i_{L}\left(t\right)$ maintain it's direction (top to bottom), this results to current loop (counter-clockwise) between the inductor and the capacitor, applying KCL at the output node, and summarize the total currents leaving that node, I get that:

$$
i_{C}\left(t\right)=-i_{L}\left(t\right)-\frac{v\left(t\right)}{R}\approx -I-\frac{V}{R}
$$

### Inductor Volt-Second Balance

The average voltage across the inductor in one period is zero:

$$\begin{aligned}
0&=\int_{0}^{T_{s}}v_{L}\left(t\right)d\tau=\int_{0}^{D_{1}T_{s}}v_{L}\left(t\right)d\tau+\int_{D_{1}T_{s}}^{T_{s}}v_{L}\left(t\right)d\tau\\
&=V_{g}D_{1}T_{s}+VD_{1}'T_{s}\Longleftrightarrow V_{g}D_{1}+VD_{1}'=0
\end{aligned}
$$

$$
\Rightarrow \boxed{V=-\frac{D_{1}}{D_{1}'}V_{g}}
$$ {#eq-Q2A-input-output-voltage}

::: {.callout-note appearance="minimal"}
#### Reminder:

$V$ is the average output voltage, and $V_g$ is the source voltage.
:::

### Capacitor Charge (Amp-Second) Balance

The average current through the capacitor in one period is zero:

$$\begin{aligned}
0&=\int_{0}^{T_{s}}i_{C}\left(t\right)d\tau=\int_{0}^{D_{1}T_{s}}i_{C}\left(t\right)d\tau+\int_{D_{1}T_{s}}^{T_{s}}i_{C}\left(t\right)d\tau\\
&= -\frac{V}{R}D_{1}T_{s}+\left(-I-\frac{V}{R}\right)D_{1}'T_{s}\\
\Longleftrightarrow 0&=-\frac{V}{R}D_{1}+\left(-I-\frac{V}{R}\right)D_{1}'
=-\frac{V}{R}D_{1}-ID_{1}'-\frac{V}{R}D_{1}'\\&=-ID_{1}'-\frac{V}{R}\left(D_{1}+D_{1}'\right)=-ID_{1}'-\frac{V}{R}\
\end{aligned}
$$

$$
\Rightarrow \boxed{I=-\frac{V}{RD_{1}'}}
$$ {#eq-Q2A-average-inductor-current}

::: {.callout-note appearance="minimal"}
#### Reminder:

$I$ is the average inductor current.
:::

### Inductor Current Ripple in CCM

The inductor current ripple, denoted as $\Delta i$ (where the total [peak-to-peak ripple is strictly defined as $2\Delta i$]{.mark}), is essential to find the boundary between CCM and DCM. To find the current ripple I will analyze the rate of change of the inductor current, from Farady's law of induction, the rate of change (aka slope) of the inductor current is proportional to the applied voltage:

$$
\frac{d i_{L}\left(t \right)}{dt}=\frac{v_{L}\left(t\right)}{L}
$$

In phase 1, $v_{L}\left(t\right)=V_{g}$. therefore, the slope of the inductor current is constant and positive:

$$
\frac{d i_{L}\left(t\right)}{dt} = \frac{V_{g}}{L}
$$

because $i_{L}\left(D_{1}T_{s}\right)-i_{L}\left(0\right)=I+\Delta i  -\left(I - \Delta i\right)= 2\Delta i$, I can substitute this into a slop line equation and get $\Delta i$:

$$
\begin{gathered}
m = \frac{\Delta y}{\Delta x} = \frac{\text{vertical change} }{\text{horizontal change} }\\
\rightarrow \frac{V_{g}}{L}=\frac{2\Delta i}{D_{1}T_{s}}\\
\end{gathered}
$$

$$
\Rightarrow\boxed{\Delta i=\frac{V_{g}D_{1}T_{s}}{2L}}
$$ {#eq-Q2A-delta-i}

### DCM mode condition

::: {.callout-note appearance="minimal"}
#### Reminder:

$$
I \lt \Delta I \Longrightarrow\text{DCM mode}
$$
:::

first I'll plug in $I$ and $\Delta I$ I found on equations [-@eq-Q2A-average-inductor-current] and [-@eq-Q2A-delta-i]:

$$
I=-\frac{V}{RD_{1}'}\lt \Delta i=\frac{V_{g}D_{1}T_{s}}{2L}
$$

In the left hand side the I can express the output voltage, $V$ , as function of the input voltage, $V_{g}$ , by plug in [@eq-Q2A-input-output-voltage], this will result the following Inequality:

$$
I=-\frac{V}{RD_{1}'}=-\frac{-\frac{D_{1}}{D_{1}'}V_{g}}{RD_{1}'}=\frac{D_{1}V_{g}}{R\left(D_{1}'\right)^{2}} \lt \frac{V_{g}D_{1}T_{s}}{2L}
$$

reordering that inequality:

$$
\begin{gathered}
\frac{\cancel{D_{1}V_{g}}}{R\left(D_{1}'\right)^{2}} \lt \frac{\cancel{V_{g}D_{1}}T_{s}}{2L}\\
\frac{1}{R\left(D_{1}'\right)^{2}} \lt \frac{T_{s}}{2L}\\
\frac{2L}{RT_{s}} \lt \left(D_{1}'\right)^{2}=\left(1-D_{1}\right)^{2}
\end{gathered}
$$

1.  on the left side I got "constant", $K$, that depend on $L,\, R,\, T_{s}$

    $K=\frac{2L}{RT_{s}}$ .

2.  on the right side I got function $K_{crit}$ whose argument is $D_{1}$:

    $K_{crit}=\left(1-D_{1}\right)^{2}$ .

and, the converter operates in DCM when $K \lt K_{crit}$. $\square$

{{< pagebreak >}}

## Question B:

Find the voltage gain $V/V_{g}$, when the converter operate at DCM mode.

:::: {#fig-Inductor-waveform layout-ncol=2}
```{python}
#| echo: false 
#| warning: true
#| error: true
#| output: asis
#| include: true
import numpy as np
from sympy import *
from sympy.abc import x
from tikzpy import Point, TikzPicture

def xy_axes(origin=Point(0, 0), x_min=-4, x_max=4, y_min=-4, y_max=4, x_label="$X$", y_label="$Y$", tikzPicture=TikzPicture()):
    x_axis = dict()
    x_axis["left"] = tikzPicture.line((x_min, origin.y), origin, options="Gray!50, -")
    x_axis["right"] = tikzPicture.line(origin, (x_max, origin.y), options="Gray!50, ->")
    x_axis["x_label"] = tikzPicture.node(x_axis["right"].end - (0.3, 0.3), text=x_label)
    y_axis = dict()
    y_axis["down"] = tikzPicture.line((origin.x, y_min), origin, options="Gray!50, -")
    y_axis["up"] = tikzPicture.line(origin, (origin.x, y_max), options="Gray!50, ->")
    y_axis["y_label"] = tikzPicture.node(y_axis["up"].end + (0.3, 0.3), text=y_label)
    return x_axis, y_axis

```

:::{#fig-VL-t-curve}
```{python}
#| echo: false 
#| warning: true
#| error: true
#| output: asis
#| include: true
# VL-t curve
VL_tikz = TikzPicture()
VLorigin = Point(0, 0)
xy_axes(
    origin=VLorigin,
    x_min=-1,
    x_max=8,
    y_min=-3,
    y_max=3,
    x_label="$t$",
    y_label="$v_L(t)$",
    tikzPicture=VL_tikz,
)
VL_points = [(0, 0), (0, 2), (2, 2), (2, -2), (4, -2), (4, 0), (6, 0), (6, 2), (7, 2)]
VL_t_curve = VL_tikz.draw_segments(VL_points, circular=False, options="Blue, thick")
# annotate the VL-t curve
VL_tikz.node(VL_t_curve[((0, 2), (2, 2))].midpoint(), text="$V_{g}$", options="above")
vl_d1 = VL_t_curve[((0, 2), (2, 2))].shift(0, -2.1)
vl_d1.options = "<->, black"
VL_tikz.draw(vl_d1)
VL_tikz.node(vl_d1.midpoint(), text="$D_{1}T_{s}$", options="below")
VL_tikz.node(VL_t_curve[((2, -2), (4, -2))].midpoint(), text="$V$", options="above")
vl_d2 = VL_t_curve[((2, -2), (4, -2))].shift(0, 1.9)
vl_d2.options = "<->, black"
VL_tikz.draw(vl_d2)
VL_tikz.node(vl_d2.midpoint(), text="$D_{2}T_{s}$", options="below")
VL_tikz.node(VL_t_curve[((4, 0), (6, 0))].midpoint(), text="$0$", options="above")
vl_d3 = VL_t_curve[((4, 0), (6, 0))].shift(0, -0.1)
vl_d3.options = "<->, black"
VL_tikz.draw(vl_d3)
VL_tikz.node(vl_d3.midpoint(), text="$D_{3}T_{s}$", options="below")
print(VL_tikz.code())
```

Voltage across the inductor, $v_L(t)$.
:::

:::{#fig-IL-t-curve}
```{python}
#| echo: false 
#| warning: true
#| error: true
#| output: asis
#| include: true
# IL-t curve
IL_tikz = TikzPicture()
ILorigin = Point(0, 0)
xy_axes(
    origin=ILorigin,
    x_min=-1,
    x_max=8,
    y_min=-3,
    y_max=3,
    x_label="$t$",
    y_label="$i_L(t)$",
    tikzPicture=IL_tikz,
)
IL_points = [(0, 0), (2, 2), (4, 0), (6, 0), (8, 2)]
IL_t_curve = IL_tikz.draw_segments(IL_points, circular=False, options="Blue, thick")
# annotate the IL-t curve
il_d1 = IL_tikz.line((2, 2), (2, 0), options="black, dashed")
IL_tikz.node(il_d1.end, text="$D_{1}T_{s}$", options="below")
IL_tikz.node((4, 0), text="$\\left(D_{1}+D_{2}\\right)T_{s}$", options="below")
IL_tikz.node((6, 0), text="$T_{s}$", options="below")
il_d2 = IL_t_curve[((0, 0), (2, 2))].shift(0.5, 0)
IL_tikz.node(il_d2.midpoint(), text="$\\frac{V_{g}}{L}$", options="")
il_d3 = IL_t_curve[((2, 2), (4, 0))].shift(-0.5, 0)
IL_tikz.node(il_d3.midpoint(), text="$\\frac{V}{L}$", options="")
IL_tikz.node((2, 2), text="$i_{pk}=\\frac{V_{g}}{L}D_{1}T_{s}$", options="above")
print(IL_tikz.code())
```

Current through the inductor, $i_L(t)$.
:::

Inductor waveforms for DCM mode
:::: 

::: {.callout-note appearance="minimal"}
#### Reminder:

In DCM mode, we can't substitute currents with their average values, instead we have to calculate the integrals directly to find the connection to average voltages. 
:::


Following the general Methodology for DCM Analysis described in tutorial 5, firstly, I will write the inductor voltage-second balance, using the inductor voltage waveform shown in figure [-@fig-VL-t-curve], the equation for the inductor voltage-second balance is:
$$\begin{gathered}
D_{1}V_{g}+D_{2}V+D_{3}\cdot 0=0\\
V=-\frac{D_{1}}{D_{2}}V_{g}
\end{gathered}
$${#eq-Q2B-input-output-voltage}

Now, I will write the capacitor charge balance equation, knowing that the average current through the capacitor must be zero:
$$\begin{gathered}
\frac{1}{T_{s}} \int_{0}^{T_{s}} i_{c}\left(t\right)dt=0\\
\frac{1}{T_{s}} \int_{0}^{T_{s}} i_{diode}\left(t\right) - \frac{v\left(t\right)}{R} dt=0
\end{gathered}
$$

substituting the voltage, $v\left(t\right)$, with it's average voltage, and we are getting that the average current through the diode must be equal to the average current through the load resistor: 
$$
\frac{1}{T_{s}} \int_{0}^{T_{s}} i_{diode}\left(t\right) dt = -\frac{V}{R}
$${#eq-Q2B-diode-current-integration}

using equation [@eq-Q2A-delta-i], the peak inductor current, $i_{pk}$, is $i_{pk}=2\Delta i=\frac{V_{g}D_{1}T_{s}}{L}$, and the current that flows through the diode is the current that flows through the inductor during the second phase, therefore, the area under the diode current waveform is the charge delivered to the load during one period, dividing that by the period will give us the average current through the diode, which is equal to the average current through the load resistor, $V/R$, as shown in [@fig-Idiode-t-curve],  the area under the diode current waveform is the area of a triangle with base $D_{2}T_{s}$ and height $i_{pk}$, therefore, the average current through the diode is:
$$\begin{aligned}
\frac{1}{T_{s}} \int_{0}^{T_{s}} i_{diode}\left(t\right) dt &= \frac{1}{T_{s}}\cdot\text{Area of the triangle}\\
&=\frac{1}{\cancel{T_{s}}}\cdot\frac{1}{2}i_{pk}D_{2}\cancel{T_{s}}\\ 
&=\frac{1}{2}\frac{V_{g}D_{1}T_{s}}{L}D_{2}
\end{aligned}
$$

and equating that to $V/R$: 
$$
\frac{1}{2}\frac{V_{g}D_{1}T_{s}}{L}D_{2}=-\frac{V}{R}
$${#eq-Q2B-diode-current-integration-result}

now, I got two equations, equation [@eq-Q2B-input-output-voltage] and equation [@eq-Q2B-diode-current-integration-result], with two unknowns, $V$ and $D_{2}$, I'll solve those two equations by substituting $V$ from the first equation into the second one:
$$\begin{aligned}
\cancel{-}\frac{\cancel{-}\frac{\cancel{D_{1}}}{D_{2}}\cancel{V_{g}}}{R}&=\frac{1}{2}\frac{\cancel{V_{g}D_{1}}T_{s}}{L}D_{2}\\
\frac{1}{D_{2}R} &= \frac{D_{2}T_{s}}{2L}\\
\rightarrow&D_{2}^{2}=\frac{2L}{RT_{s}}\rightarrow \boxed{D_{2}=\sqrt{\frac{2L}{RT_{s}}}}\\
\rightarrow V&=-\frac{D_{1}}{D_{2}}V_{g}=-\frac{D_{1}}{\sqrt{\frac{2L}{RT_{s}}}}V_{g}\Rightarrow \boxed{\frac{V}{V_{g}}=-\frac{D_{1}}{\sqrt{\frac{2L}{RT_{s}}}}}
\end{aligned}
$$

and I we use the definition of $K$ I found in question A, which is $K=\frac{2L}{RT_{s}}$, the voltage gain can be expressed as function of $K$ and $D_{1}$:
$$
\frac{V}{V_{g}}=-\frac{D_{1}}{\sqrt{K}}
$${#eq-Q2B-voltage-gain-with-K}

:::{#fig-Idiode-t-curve}
```{python}
#| echo: false 
#| warning: true
#| error: true
#| output: asis
#| include: true
# IL-t curve
Idiode_tikz = TikzPicture()
Idiode_origin = Point(0, 0)
xy_axes(
    origin=Idiode_origin,
    x_min=-1,
    x_max=8,
    y_min=-3,
    y_max=3,
    x_label="$t$",
    y_label="$i_{diode}(t)$",
    tikzPicture=Idiode_tikz,
)
Idiode_points = [(0, 0), (2, 0), (2, 2), (4, 0), (6, 0), (8, 0)]
# Idiode_t_curve = Idiode_tikz.draw_segments(Idiode_points, circular=False, options="Blue, thick")
# annotate the IL-t curve
idiode_d1 = Idiode_tikz.line((0, -0.1), (2, -0.1), options="|-|, black, dashed")
Idiode_tikz.node(idiode_d1.midpoint(), text="$D_{1}T_{s}$", options="below")
idiode_d2 = Idiode_tikz.line((2, -0.1), (4, -0.1), options="|-|, black, dashed")
Idiode_tikz.node(idiode_d2.midpoint(), text="$D_{2}T_{s}$", options="below")
idiode_d3 = Idiode_tikz.line((4, -0.1), (6, -0.1), options="|-|, black, dashed")
Idiode_tikz.node(idiode_d3.midpoint(), text="$D_{3}T_{s}$", options="below")
Idiode_tikz.node((2, 2), text="$i_{pk}=\\frac{V_{g}}{L}D_{1}T_{s}$", options="right")
idiode_triangle = Idiode_tikz.plot_coordinates(
    Idiode_points, options="Blue, thick, fill={ProcessBlue!50}", action="filldraw"
)
print(Idiode_tikz.code())
```

Current through the diode, $i_{diode}(t)$.
:::


{{< pagebreak >}}

## Question C:

Given $K=0.1$ and $D_{1}=0.3$ calculate the relative time of each phase, $D_{1},\, D_{2},\, D_{3}$, and plot the waveforms of the inductor voltage and current.

First, I will ensure that the converter is operating in DCM mode by checking the condition I found in question A, which is $K \lt K_{crit}$, where $K_{crit}=\left(1-D_{1}\right)^{2}$:
$$
K=0.1 \lt K_{crit}=\left(1-0.3\right)^{2}=0.49 \Rightarrow\text{DCM mode}
$$

now, I will calculate $D_{2}$, in question B, I found that $D_{2}=\sqrt{\frac{2L}{RT_{s}}}$, and in question A, I found that $K=\frac{2L}{RT_{s}}$, therefore, $D_{2}=\sqrt{K}$:
$$
D_{2}=\sqrt{K}=\sqrt{0.1}\approx 0.316
$$

now, I can calculate $D_{3}$ by using the fact that $D_{1}+D_{2}+D_{3}=1$:
$$
D_{3}=1-D_{1}-D_{2}=1-0.3-0.316=0.384
$$

and the waveforms of the inductor voltage and current are shown in [@fig-Q-C-VL-t-curve] and  [@fig-Q-C-IL-t-curve], respectively.


:::: {#fig-question-C-inductor-waveform layout-ncol=2}
```{python}
#| echo: false 
#| warning: true
#| error: true
#| output: asis
#| include: true
import numpy as np
from sympy import *
from sympy.abc import x
from tikzpy import Point, TikzPicture


def xy_axes(
    origin=Point(0, 0),
    x_min=-4,
    x_max=4,
    y_min=-4,
    y_max=4,
    x_label="$X$",
    y_label="$Y$",
    tikzPicture=TikzPicture(),
):
    x_axis = dict()
    x_axis["left"] = tikzPicture.line((x_min, origin.y), origin, options="Gray!50, -")
    x_axis["right"] = tikzPicture.line(origin, (x_max, origin.y), options="Gray!50, ->")
    x_axis["x_label"] = tikzPicture.node(x_axis["right"].end - (0.3, 0.3), text=x_label)
    y_axis = dict()
    y_axis["down"] = tikzPicture.line((origin.x, y_min), origin, options="Gray!50, -")
    y_axis["up"] = tikzPicture.line(origin, (origin.x, y_max), options="Gray!50, ->")
    y_axis["y_label"] = tikzPicture.node(y_axis["up"].end + (0.3, 0.3), text=y_label)
    return x_axis, y_axis


D1 = 0.3
D2 = 0.316
D3 = 0.384


def round_list(lst, decimals=3):
    return [tuple(round(val, decimals) for val in point) for point in lst]
```

:::{#fig-Q-C-VL-t-curve}
```{python}
#| echo: false 
#| warning: true
#| error: true
#| output: asis
#| include: true
# Q-C-VL-t curve
QC_VL_tikz = TikzPicture()
QC_VLorigin = Point(0, 0)
xy_axes(
    origin=QC_VLorigin,
    x_min=-0.1,
    x_max=(6 + D1 * 2 + D2 * 2 + D3 * 2) * 1.1,
    y_min=-2.5,
    y_max=2.5,
    x_label="$t$",
    y_label="$v_L(t)$",
    tikzPicture=QC_VL_tikz,
)
QC_VL_points = [
    (0, 0),
    (0, 2),
    (2 + D1 * 2, 2),
    (2 + D1 * 2, -2),  # D1 segment
    (4 + D1 * 2 + D2 * 2, -2),
    (4 + D1 * 2 + D2 * 2, 0),  # D2 segment
    (6 + D1 * 2 + D2 * 2 + D3 * 2, 0),  # D3 segment
]
#QC_VL_points = round_list(QC_VL_points, 3)
QC_VL_t_curve = QC_VL_tikz.draw_segments(QC_VL_points, circular=False, options="Blue, thick")
# annotate the VL-t curve
D1_line=QC_VL_tikz.line((0, 0), (2+D1*2, 0), options="|-|, black, dashed")
QC_VL_tikz.node(D1_line.midpoint(), text=f'$D_{1}T_{s}={D1:.3f} T_{s}$', options="below")
D2_line=QC_VL_tikz.line((2+D1*2, 0), (4+D1*2+D2*2, 0), options="|-|, black, dashed")
QC_VL_tikz.node(D2_line.midpoint(), text=f'$D_{2}T_{s}={D2:.3f} T_{s}$', options="below")
D3_line=QC_VL_tikz.line((4+D1*2+D2*2, 0), (6+D1*2+D2*2+D3*2, 0), options="|-|, black, dashed")
QC_VL_tikz.node(D3_line.midpoint(), text=f'$D_{3}T_{s}={D3:.3f} T_{s}$', options="below")
QC_VL_tikz.node(QC_VL_t_curve[((0, 2), (2 + D1 * 2, 2))].midpoint(), text="$V_{g}$", options="above")
QC_VL_tikz.node(QC_VL_t_curve[((2 + D1 * 2, -2), (4 + D1 * 2 + D2 * 2, -2))].midpoint(), text="$V$", options="above")
QC_VL_tikz.node(QC_VL_t_curve[((4 + D1 * 2 + D2 * 2, 0), (6 + D1 * 2 + D2 * 2 + D3 * 2, 0))].midpoint(), text="$0$", options="above")
print(QC_VL_tikz.code())
```

Voltage across the inductor, $v_L(t)$.
:::

:::{#fig-Q-C-IL-t-curve}
```{python}
#| echo: false 
#| warning: true
#| error: true
#| output: asis
#| include: true
# QC-IL-t curve
QC_IL_tikz = TikzPicture()
QC_ILorigin = Point(0, 0)
xy_axes(
    origin=QC_ILorigin,
    x_min=-1,
    x_max=8,
    y_min=-2.5,
    y_max=2.5,
    x_label="$t$",
    y_label="$i_L(t)$",
    tikzPicture=QC_IL_tikz,
)
IL_points = [
    (0, 0),
    (2 + D1 * 2, 2),
    (4 + D1 * 2 + D2 * 2, 0),
    (6 + D1 * 2 + D2 * 2, 0),
]
IL_t_curve = QC_IL_tikz.draw_segments(IL_points, circular=False, options="Blue, thick")
# annotate the IL-t curve
il_d1 = QC_IL_tikz.line((2 + D1 * 2, 2), (2 + D1 * 2, 0), options="black, dashed")
QC_IL_tikz.node(il_d1.end, text=f"$D_{1}T_{s}={D1:.3f} T_{s}$", options="below")
aux = QC_IL_tikz.node(
    (4 + D1 * 2 + D2 * 2, 0),
    text="$\\left(D_{1}+D_{2}\\right)T_{s}$",
    options="below",
)
QC_IL_tikz.node(
    aux.position + (0, -0.5),
    text=f"$={D1+D2:.3f} T_{s}$",
    options="below",
)
QC_IL_tikz.node((6 + D1 * 2 + D2 * 2, 0), text="$T_{s}$", options="below")
il_d2 = IL_t_curve[((0, 0), (2 + D1 * 2, 2))].shift(0.5, 0)
QC_IL_tikz.node(il_d2.midpoint(), text="$\\frac{V_{g}}{L}$", options="")
il_d3 = IL_t_curve[((2 + D1 * 2, 2), (4 + D1 * 2 + D2 * 2, 0))].shift(-0.5, 0)
QC_IL_tikz.node(il_d3.midpoint(), text="$\\frac{V}{L}$", options="")
QC_IL_tikz.node(
    (2 + D1 * 2, 2), text="$i_{pk}=\\frac{V_{g}}{L}D_{1}T_{s}$", options="above"
)
print(QC_IL_tikz.code())
```

Current through the inductor, $i_L(t)$.
:::

Inductor waveforms for DCM mode with $K=0.1$ and $D_{1}=0.3$.
:::: 

{{< pagebreak >}}

## Question D:

What happen to $V$ when there is no load connected to the output $\left(R \to \infty \right)$?

In question B, I found that the voltage gain of the converter in DCM mode is $\frac{V}{V_{g}}=-\frac{D_{1}}{\sqrt{K}}$, where $K=\frac{2L}{RT_{s}}$. when there is no load connected to the output, $R \to \infty$, therefore 
$V=V_{g}\cdot "-\infty" \Rightarrow V\to -\infty$.

In energy perspective, the energy stored in the inductor during the first phase will be delivered to the output during the second phase, but since there is no load at the output to dissipate the power, the absolute value of the voltage will increase to infinity.