---
title: "Homework 2 - Advanced Converter Topologies"
subtitle: "Course 00440139 - Winter 2026"
author: "Doron Shpigel 313545600"
format:
  html:
    toc: true
    toc-depth: 2
    number-sections: true
    html-math-method: katex
---

# Problem 1:

```{python}
#|echo: false 
#|output: true
from contextlib import redirect_stdout, redirect_stderr
import io
import warnings
import logging
from lcapy import *

warnings.filterwarnings('ignore')
logging.getLogger('lcapy').setLevel(logging.ERROR)

with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
    Converter = Circuit(r"""
    #create voltage source
        V ._plus  0 {V_g  }; down, size=2
    #create inductor
        L L.1 L.2; right, l= L, size=1.5
    # create SW1
        SW1 ._COM ._NC ._NO spdt; invert, l={}
        A1 SW1._NC; l=1, anchor=south west
        A2 SW1._NO; l=2, anchor=north west
    #create SW2
        SW2 ._COM ._NO ._NC spdt; mirror, l={}
        A3 SW2._NC; l=1, anchor=north west
        A4 SW2._NO; l=2, anchor=south west
    #create RC
        C C.1 C.2; right, l= C
        R R.1 R.2; right, l= R, v={$+\quad V\quad -$}
        O _RC1 C.1; right, rotate=45, size=0.75, 
        O _RC1 R.1; right, rotate=-45, size=0.75
        W _RC1 C.1; steps=|-, free
        W _RC1 R.1; steps=|-, free
        ;;\draw (_RC1)node[circ];
        O C.2 _RC2; right, rotate=-45, size=0.75
        O R.2 _RC2; right, rotate=45, size=0.75
        W C.2 _RC2; steps=-|, free
        W R.2 _RC2; steps=-|, free
        ;;\draw (_RC2)node[circ];
    #create connections:
    # connect RC to switches
        W SW1._COM _RC1; right, size=0.1
        W _RC2 SW2._COM; right, size=0.1
    # connect voltage source to inductor
        W V._plus L.1; right, size=0
    # connect inductor L to switches
        W L.2 SW1._NC; down
        W L.2 SW2._NO; steps=-|, free
    # connect ground to switches
        O SW1._NO 0_0; down, size=1
        W SW1._NO 0_0; down
        ;;\draw (0_0)node[circ];
        W 0 0_0; right
        W 0_0 SW2._NC; steps=-|, free
        ; autoground=false, draw_nodes=connections, label_ids=false, label_nodes=alpha, european voltages""")
    Converter.draw()
```

-   The inductor has ohmic resistance $R_L$.
-   All the other losses are neglected.
-   The switches operate in a complementary manner, such that:
    -   The switches on mode $1$ in time interval $\left[0, DT_s\right]$.
    -   The switches on mode $2$ in time interval $\left[D T_s, T_s\right]$.

## Question A:

The voltage amplification of the converter $V/V_g$: I will label the average current flows through the inductor as $I$, when the switches are in mode 1, the voltage across the inductor is: 
$$
V_L = V_g - V- V_L =V_g - V - I R_L
$$

When the switches are in mode 2, the voltage across the inductor is: 
$$
V_L = V_g - (-V) - V_L = V_g + V - I R_L
$$

Since the average voltage across the inductor over a full switching period is zero, I can write:
$$\begin{gather*}
D\left(V_g - V - I R_L \right) + D'\left(V_g + V - I R_L \right) = 0 \\
D\left(V_g - V - I R_L \right) + \left(1-D\right)\left(V_g + V - I R_L \right) = 0 \\
D\left(V_g - V - I R_L \right) - D\left(V_g + V - I R_L \right) + V_g +V - I R_L = 0 \\
D\left(\cancel{V_g} - V \cancel{- I R_L} \right) + D\left(\cancel{- V_g}- V \cancel{+ I R_L} \right) + V_g + V - I R_L = 0 \\
-2DV+ V_g + V - I R_L = 0\\
-2D+1 = -2D + D' + D = D' - D \rightarrow V_g + \left( D' - D\right) V - I R_L = 0 \tag{1}
\end{gather*}
$$

When the switches change their state, the current through the capacitor changes it's direction. Using KCL, I can express the average current through the capacitor at each mode, as follows: In mode 1: 
$$
I_{C_\text{mode 1}} = I - I_R = I - \frac{V}{R}
$$

In mode 2: 
$$
I_{C_\text{mode 2}} = -I - I_R = -I - \frac{V}{R} 
$$

Because the average current through the capacitor over a full switching period is zero, I can write:
$$\begin{gather*}
D\cdot I_{C_\text{mode 1}} + D' \cdot I_{C_\text{mode 2}} = 0 \\
D\left( I - \frac{V}{R} \right) + D'\left( -I - \frac{V}{R} \right) = 0\\
D\left( I - \frac{V}{R} \right) + \left( 1-D \right)\left( -I - \frac{V}{R} \right) = 0 \\
D\left( I - \frac{V}{R} \right) - D\left( -I - \frac{V}{R} \right) - I - \frac{V}{R} = 0 \\
D\left( I \cancel{- \frac{V}{R}} \right) + D\left( I \cancel{+ \frac{V}{R}} \right) - I - \frac{V}{R} = 0 \\
DI + DI - I - \frac{V}{R} = 0 \\
DI -(1-D)I= \frac{V}{R} \\
I = \frac{V}{R\left( D-D' \right)} \tag{2}
\end{gather*}
$$

Now, I can substitute equation (2) into equation (1), to find expression for $V/V_g$:
$$\begin{gather*}
V_g + \left( D' - D\right) V - R_L \cdot \frac{V}{R\left( D-D' \right)} = 0\\
V_g = R_L \cdot \frac{V}{R\left( D-D' \right)} - \left( D' - D\right) V \\
V_g = R_L \cdot \frac{V}{R\left( D-D' \right)} + \left( D - D' \right) V \\
V_g = V \cdot \left(D-D'\right) \cdot \left( 1 + \frac{R_L}{R\left( D-D' \right)^2} \right) \\
\frac{V}{V_g} = \frac{1}{\left(D-D'\right)} \cdot \frac{1}{1 + \frac{R_L}{R}\cdot \frac{1}{\left( D-D' \right)^2}}\\
\frac{V}{V_g} = \frac{1}{2D -1}\cdot \frac{1}{1 + \frac{R_L}{R}\cdot \frac{1}{\left( 2D -1 \right)^2}}
\end{gather*}
$$

## Question B:

```{python}
#|echo: false
#|output: true
import numpy as np
import matplotlib.pyplot as plt
D = np.linspace(0,1,1000)
voltage_gain = lambda D, ratio: 1/ (2*D -1) * 1/(1 + ratio / (2*D -1)**2)

plt.figure(figsize=(10,6))
plt.plot(D, voltage_gain(D, 0), label=r'$R_L/R = 0$')
plt.plot(D, voltage_gain(D, 0.01), label=r'$R_L/R = 0.01$')
plt.plot(D, voltage_gain(D, 0.05), label=r'$R_L/R = 0.05$')
plt.legend()
plt.title('Voltage Gain $V/V_g$ vs Duty Cycle for Different $R_L/R$ Ratios')
plt.xlabel('Duty Cycle D')
plt.ylabel('Voltage Gain \n$V/V_g$', rotation=0, ha='right')
plt.ylim(-6, 6)
plt.grid()
plt.show()
```

